version: 3.1.0

pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    # embedding: pyannote/wespeaker-voxceleb-resnet34-LM  # if you want to use the HF model
    embedding: /workspace/notebooks/models/pyannote_model_wespeaker-voxceleb-resnet34-LM.bin  # if you want to use the local model
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    # segmentation: pyannote/segmentation-3.0  # if you want to use the HF model
    segmentation: /workspace/notebooks/models/pyannote_model_segmentation-3.0.bin  # if you want to use the local model
    segmentation_batch_size: 32

params:
  clustering:
    method: centroid
    min_cluster_size: 15
    threshold: 0.7153814381597874
  segmentation:
    min_duration_off: 0.5817029604921046
    threshold: 0.4442333667381752